Feature/38307 ubuntu 20 04 support
magenta-aps/setup_minion pull request #2
Opened 2020-09-29 11:23 UTC by Skeen

2020-09-29 11:51 UTC, Maxtaager requested changes

2020-09-29 11:51 UTC, Maxtaager commented on setup_minion.sh
> +wget -O - https://repo.saltstack.com/py3/ubuntu/${UBUNTU_VERSION}/amd64/${SALT_VERSION}/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
hvis 18.04 bør vi stadig benytte 2019.2 indtil master er upgarderet..

2020-09-30 08:24 UTC, Skeen commented on setup_minion.sh
> +wget -O - https://repo.saltstack.com/py3/ubuntu/${UBUNTU_VERSION}/amd64/${SALT_VERSION}/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
Changes made.

2020-10-01 08:47 UTC, carlbordum commented
Hvis det er blevet testet på begge Ubuntu versioner, er det her fint med mig :+1:

2020-10-01 12:09 UTC, merged